name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_CONTAINER_REGISTRY: mscwoundcare.azurecr.io
  BACKEND_CONTAINER_NAME: msc-admin-assist-api
  FRONTEND_CONTAINER_NAME: msc-admin-assist-frontend
  AZURE_WEBAPP_NAME: msc-wound-care-app
  RESOURCE_GROUP: msc-wound-care

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd server && npm ci
        cd ../client && npm ci
    
    - name: Run backend tests
      run: cd server && npm test
    
    - name: Run frontend tests
      run: cd client && npm test
    
    - name: Build applications
      run: |
        cd server && npm run build
        cd ../client && npm run build
    
    - name: Run linting
      run: |
        cd server && npm run lint
        cd ../client && npm run lint

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push backend container
      uses: docker/build-push-action@v4
      with:
        context: ./server
        push: true
        tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.BACKEND_CONTAINER_NAME }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and push frontend container
      uses: docker/build-push-action@v4
      with:
        context: ./client
        push: true
        tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.FRONTEND_CONTAINER_NAME }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Deploy to Azure Container Apps
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        resource-group: ${{ env.RESOURCE_GROUP }}
        images: |
          ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.BACKEND_CONTAINER_NAME }}:${{ github.sha }}
          ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.FRONTEND_CONTAINER_NAME }}:${{ github.sha }} 